{% set name = "geospatial" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geospatial-{{ version }}.tar.gz
  sha256: 9316104ce252d77e4863769bba27fba8af3f37afa06558b1ccc4f86351777857

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - black-jupyter
    - bump2version
    - codespell
    - cartopy
    - dask-geopandas
    - geemap
    - geopandas
    - here-map-widget-for-jupyter
    - httplib2shim
    - ipygany
    - ipynb-py-convert
    - ipyvtklink
    - keplergl
    - laspy
    - leafmap
    - localtileserver
    - mapboxgl
    - netcdf4
    - osmnx
    - owslib
    - rasterio
    - rasterstats
    - panel
    - palettable
    - plotly
    - psycopg2
    - pydeck
    - python-mss
    - pyntcloud
    - pyvista
    - rio-cogeo
    - rioxarray
    - sqlalchemy
    - streamlit-folium
    - voila
    - xarray-spatial
    - google-api-python-client <2  # required for earthengine-api

test:
  imports:
    - geospatial
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/giswqs/geospatial
  summary: A Python package for geosptial analysis and data visualization
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://geospatial.gishub.org
  dev_url: https://github.com/giswqs/geospatial

extra:
  recipe-maintainers:
    - giswqs
