{% set name = "geospatial" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geospatial-{{ version }}.tar.gz
  sha256: 7c55793bd50a86c6cbfa82d10f20f80821083ba9bfa245e3a5cf22761bc8581b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - black-jupyter
    - bump2version
    - cartopy
    - cenpy
    - codespell
    - contextily
    - dask-geopandas
    - datashader
    - earthengine-api
    - earthpy
    - easystac
    - eemont
    - eomaps
    - folium >=0.12.1
    - geemap >=0.14.1
    - gemgis
    - geoalchemy2
    - geocube
    - geopandas >=0.10.2
    - geosnap
    - geoviews
    - h3
    - h3-py
    - here-map-widget-for-jupyter
    - hvplot
    - ipygany
    - ipyleaflet >=0.16.0
    - ipynb-py-convert
    - ipyvtklink
    - jupytext
    - keplergl
    - laspy
    - leafmap >=0.9.5
    - lidar
    - localtileserver >=0.5.8
    - mapboxgl
    - movingpandas
    - netcdf4
    - odc-stac
    - osmnx
    - owslib
    - panel
    - palettable
    - pillow 
    - planetary-computer
    - plotly
    - proplot
    - psycopg2
    - pydeck
    - pygis >=0.3.1
    - pysal
    - python-mss
    - pyntcloud
    - pyvista
    - radiant-mlhub
    - rasterio
    - rasterstats
    - rio-cogeo
    - rioxarray
    - s2cloudless
    - sarpy
    - satpy
    - scholarpy
    - sentinelsat
    - shapely
    - sliderule
    - spyndex
    - sqlalchemy
    - stackstac
    - streamlit-folium
    - tropycal
    - voila
    - xarray-spatial
    - xmovie
    - wxee

test:
  imports:
    - geospatial
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://github.com/giswqs/geospatial
  summary: A Python package for installing commonly used packages for geospatial analysis and data visualization with only one command.  
  description: A Python package for installing commonly used packages for geospatial analysis and data visualization with only one command. 
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://geospatial.gishub.org
  dev_url: https://github.com/giswqs/geospatial

extra:
  recipe-maintainers:
    - giswqs
